#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := 

# header files in this project
HEADERS := player.hpp

# other places to look for files for this project
SEARCH  := 

# set BMPTK to the next higher directory and defer to the Makefile.due
BMPTK := $(BMPTK)../
include $(BMPTK)Makefile.due


main.cpp: Makefile decoder.exe player.hpp
	decoder play_melody "songs/2 Pac - Changes.txt" > main.cpp
	
decoder.exe: decoder.cpp
	g++ decoder.cpp -o decoder.exe