.PHONY: clean All

All:
	@echo "----------Building project:[ practicum_3 -  ]----------"
	@cd "practicum_3" && "$(MAKE)" -f  "practicum_3.mk"
clean:
	@echo "----------Cleaning project:[ practicum_3 -  ]----------"
	@cd "practicum_3" && "$(MAKE)" -f  "practicum_3.mk" clean
