.PHONY: clean All

All:
	@echo "----------Building project:[ practicum5_2 -  ]----------"
	@cd "practicum5_2" && "$(MAKE)" -f  "practicum5_2.mk"
clean:
	@echo "----------Cleaning project:[ practicum5_2 -  ]----------"
	@cd "practicum5_2" && "$(MAKE)" -f  "practicum5_2.mk" clean
